ENH remove weird systemd mount thingies

diff --git a/dot_bin/executable_with_gpg_mount b/dot_bin/executable_with_gpg_mount
--- a/dot_bin/executable_with_gpg_mount
+++ b/dot_bin/executable_with_gpg_mount
@@ -5,26 +5,7 @@
 bin="$1"
 shift
 
-## TODO most of this stuff could be more easily done in the rofi-extras
-## haskell code where many of the edge cases that this is hoping to avoid are
-## already strictly/brutally snuffed out by GHC's iron fist
+alias="gnupg"
 
-notify_error () {
-    notify-send --icon=dialog-error-symbolic "$1"
-}
-
-notify_info () {
-    notify-send --icon=dialog-information-symbolic "$1"
-}
-
-if ! systemctl --user is-active --quiet mount-veracrypt@gnupg.service; then
-    if systemctl --user --quiet start mount-veracrypt@gnupg.service; then
-        notify_info "Mounted $GNUPGHOME"
-        "$bin" "$@"
-    else
-        notify_error "Could not mount gnupg directory"
-        exit 1
-    fi
-else
-    "$bin" "$@"
-fi
+rofi-dev -c "$XDG_CONFIG_HOME/rofi/devices.yml" -m "$alias" \
+    && "$bin" "$@" || echo "Could not mount $alias"
